spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.43.168:3306/iVolunteer
    #    zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: abC123456!


  data:
    redis:
      password: 123456
      port: 6379
      host: 8.130.43.168

